version: 2.1
 
jobs:
  build_macos:
    resource_class: large
    macos:
      xcode: 13.2.1 # indicate your selected version of Xcode
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: brew install cmake boost icu4c
      - run:
          name: Build Kudu
          command: sh build.sh
      - store_artifacts:
          path: build/kudu
 
workflows:
  version: 2
  build:
    jobs:
      - build_macos