name: build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:


jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: >
          sudo add-apt-repository
          'deb http://mirrors.kernel.org/ubuntu hirsute main universe'

          sudo apt-get -y install build-essential git cmake
          libboost-all-dev libgmp-dev libleveldb-dev libminiupnpc-dev
          libreadline-dev libncurses5-dev libcurl4-openssl-dev
          libjsonrpccpp-dev libmicrohttpd-dev libjsoncpp-dev
          libedit-dev libz-dev gcc-11 g++-11 ccache

      - name: Gen Cache Id
        run: |
          echo "::set-output name=timestamp::$(date '+%s')"
        id: cache-id

      - name: Cache build (ubuntu)
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: build
          key: ubuntu-build-${{ secrets.CACHE_ID }}-${{ steps.cache-id.outputs.timestamp }}
          restore-keys: |
            ubuntu-build-${{ secrets.CACHE_ID }}-

      - name: Build kudu
        run: | 
          CXX=g++-11 CC=gcc-11 sh build.sh

      - name: Upload kudu artifact
        uses: actions/upload-artifact@v2
        with:
          name: kudu-ubuntu
          path: build/kudu

  build-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
    steps:
      - uses: actions/checkout@v2

      - name: Gen Cache Id
        run: |
          echo "::set-output name=timestamp::$(date '+%s')"
        id: cache-id

      - name: Cache build (macos)
        uses: actions/cache@v2
        with:
          path: build
          key: ${{matrix.os}}-build-${{ secrets.CACHE_ID }}-${{ steps.cache-id.outputs.timestamp }}
          restore-keys: |
            ${{matrix.os}}-build-${{ secrets.CACHE_ID }}-

      - name: Install dependencies
        run: brew install cmake boost icu4c

      - name: Build kudu
        run: |
          sh build.sh

      - name: Upload kudu artifact
        uses: actions/upload-artifact@v2
        with:
          name: kudu-${{matrix.os}}
          path: build/kudu
